#A list of bots that should be used
bots: #Add bots here, an example is given
#  - type: skype #The type of the bot
#    settings: #Bots may require extra settings
#        username: USERNAME #The username this bot should look for. Skype must be running with this user logged in.
#        name: Chatty #The name the bot should use.